openapi: 3.0.0
info:
  title: AI Planner API
  version: 1.0.0
  description: API for AI-powered scheduling and task management.

servers:
  - url: http://localhost:8000
    description: Local Development Server

paths:
  /tasks:
    get:
      summary: Get all tasks
      parameters:
        - in: query
          name: updated_after
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: List of tasks
    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Task created

  /calendar/events:
    get:
      summary: Get calendar events (local + external)
      parameters:
        - in: query
          name: start_date
          schema:
            type: string
            format: date
        - in: query
          name: end_date
          schema:
            type: string
            format: date
      responses:
        '200':
          description: List of events

  /ai/analyze-task:
    post:
      summary: Analyze a task and estimate duration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
      responses:
        '200':
          description: Analysis result
          content:
            application/json:
              schema:
                type: object
                properties:
                  estimated_duration_minutes:
                    type: integer
                  tags:
                    type: array
                    items:
                      type: string

  /ai/schedule:
    post:
      summary: Trigger AI scheduling for a task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                task_id:
                  type: string
                  format: uuid
      responses:
        '202':
          description: Processing started (Polling required)
          content:
            application/json:
              schema:
                type: object
                properties:
                  job_id:
                    type: string

  /ai/schedule/options/{job_id}:
    get:
      summary: Get scheduling options for a completed job
      responses:
        '200':
          description: List of options
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ScheduleOption'

components:
  schemas:
    TaskCreate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
        description:
          type: string
        deadline:
          type: string
          format: date-time
        priority:
          type: string
          enum: [low, medium, high]
        context_notes:
          type: string

    ScheduleOption:
      type: object
      properties:
        option_id:
          type: string
        start_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time
        reasoning:
          type: string
        impact_analysis:
          type: string
